insert into whse_basemapping.fwa_waterbodies_20k_50k (
  waterbody_20k_50k_id,
  watershed_group_id_20k,
  waterbody_type_20k,
  waterbody_poly_id_20k,
  waterbody_key_20k,
  fwa_watershed_code_20k,
  local_watershed_code_20k,
  watershed_group_code_20k,
  waterbody_type_50k,
  waterbody_key_50k,
  watershed_group_code_50k,
  watershed_code_50k,
  match_type
)
select
  waterbody_20k_50k_id,
  watershed_group_id_20k,
  waterbody_type_20k,
  waterbody_poly_id_20k,
  waterbody_key_20k,
  fwa_watershed_code_20k,
  local_watershed_code_20k,
  watershed_group_code_20k,
  waterbody_type_50k,
  waterbody_key_50k,
  watershed_group_code_50k,
  watershed_code_50k,
  match_type
from fwapg.fwa_waterbodies_20k_50k;
