name: test-migrations
run-name: ${{ github.actor }} Test migration sql in ephemeral db
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'db/migrations/*.sql'
env:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
jobs:
  test-migrations:
    runs-on: ubuntu-latest
    name: test-migration
    container: ghcr.io/smnorris/fwapg-loader:main
    services:
      postgres:
        image: ghcr.io/smnorris/fwapg-db:main
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Try running the migrations
        run: |
          cd db && ./migrate.sh